### PR TITLE
Keyboard Support

### PR DESCRIPTION
**Pull request by omghax**
This is a fairly major (read: breaking) change. For now I've dropped the
ability to define a tree via static markup. Instead, you must pass a
node object into the root `ivy-tree` component. At a minimum, this node
must have a `children` property which is an array of its child nodes.

The `ivy-tree` component will recursively yield each node and each of
its children, and each of their children, and so on. Here's an example
of how to use it:

``` handlebars
{{#ivy-tree node=myNode as |nodeOrDescendant|}}
  <span>{{nodeOrDescendant.name}}</span>
{{/ivy-tree}}
```

The above would output a `<span>` tag containing the name of each node.
If the node has children, it would also output a subtree which contained
a separate `<span>` for each name, and so on.

### CODE REVIEW

**Comment by omghax** [comment]
This still has some rough edges. The keyboard support seems to work as far as I can tell, but it's entirely possible I've overlooked some scenario where a certain combination of expanded / collapsed nodes causes problems (specifically with the up / down arrow keys).

@nbibler would you mind giving this a look over and let me know your thoughts?

**Comment by omghax** [comment]
This also drops the contextual component usage, so it's possible that we could make this work on Ember < 2.3 again.

**Comment by nbibler** [comment]
Functionality seems good. The only keyboard entries that appear to be missing currently are `HOME` and `END`.

As for the new usage, is it possible to dynamically set the lower-level tree classes? I have a use case right now where the top level item container (`ol`) has one class, but the next level item containers have a different one. Seemingly, I'd need to inherit/override the single component defined to pull a new attribute from the data tree provided to dynamically render a class?

**Comment by nbibler** [comment]
There also appears to be no way to differentiate a treeitem that has children vs. one that doesn't in the CSS / DOM attributes. It looks like the child `UL` is _always_ rendered even if there are no children.

**Comment by omghax** [comment]
I don't _think_ WAI-ARIA makes any prescriptions about how to indicate whether a group has children or not...seems like you should be able to manage that yourself in the template?

``` handlebars
{{#ivy-tree node=node as |nodeOrDescendant|}}
  {{#if nodeOrDescendant.children}}
    <!-- do some stuff with children here ... -->
  {{/if}}
{{/ivy-tree}}
```

**Comment by nbibler** [comment]
I think you're misunderstanding the CSS class application described... it'd be more like:

``` html
<ol class="top-level-list">
  <li>Item 1</li>
  <li>
    item 2
    <ol class="sub-level-list">
      <li>item 3</li>
    </ol>
  </li>
</ol>
```

Yes, in this particular example you _could_ have an `ol > ol` selector in the CSS, but that's a little beside the point.

In the current setup, I don't know that there's a way to customize the attributes on the generated lists without overriding the component.

**Comment by nbibler** [comment]
Seems as though the developer would need more than `{{#if nodeOrDescendant.children}}`... wouldn't an empty array still be truthy?

**Comment by omghax** [comment]
Okay, I think I understand where you're coming from. Currently there isn't a way to customize the actual rendering of the component, since the `{{ivy-treeitem}}` and `{{ivy-tree}}` invocations are happening from inside of `{{ivy-tree}}` itself (see `addon/templates/components/ivy-tree.hbs` and `addon/templates/components/ivy-treeitem.hbs`). I haven't put any effort into this yet, but it would be nice to force you to call `tree.item` or `item.group` like before, otherwise the sub-components wouldn't be rendered. This would give you an opportunity to customize the classes, etc. I _might_ have some time tonight to take a crack at it, but if you want to, feel free.

**Comment by omghax** [comment]
Also, re: falsy values, it seems that Handlebars (at least Ember's flavor of Handlebars) considers an empty array as falsy. Here's the description from the `{{if}}` helper:

> Use the if block helper to conditionally render a block depending on a property. If the property is "falsey", for example: false, undefined, null, "", 0, NaN or an empty array, the block will not be rendered.

**Comment by omghax** [comment]
After another rework, `ivy-tree` has regained the ability to work via static markup in the template, without the need for a backing model. Doing so also once again adds the requirement for contextual components, so using this in Ember < 2.3 is no longer possible.

The recursive, model-based use case can still be supported by defining a component in your app that recursively renders groups and treeitems. If this is a common enough use case, it would make sense to bake this recursive component into the addon as well. That's outside the scope of this PR though.

**Pull request merged**
